module.exports = {
	LOG:                 Symbol("LOG"),
	STATUS:              Symbol("STATUS"),
	ADDRESS:             Symbol("ADDRESS"),
	IEEE:                Symbol("IEEE"),
	ID:                  Symbol("ID"),
	TYPE:                Symbol("TYPE"),
	DEVICE:              Symbol("DEVICE"),
	DEVICES:             Symbol("DEVICES"),
	PROFILE:             Symbol("PROFILE"),
	READY:			         Symbol("READY"),
	ENDPOINT:            Symbol("ENDPOINT"),
	ENDPOINTS:           Symbol("ENDPOINTS"),
	CLUSTER:             Symbol("CLUSTER"),
	CLUSTERS:            Symbol("CLUSTERS"),
	ATTRIBUTE:           Symbol("ATTRIBUTE"),
	ATTRIBUTES:          Symbol("ATTRIBUTES"),
	ATTR_DATA:           Symbol("ATTR_DATA"),
	COMMAND:             Symbol("COMMAND"),
	COMMANDS:            Symbol("COMMANDS"),
	ACTION:              Symbol("ACTION"),
	ACTIONS:             Symbol("ACTIONS"),
	VALUE:               Symbol("VALUE"),
	VALUES:              Symbol("VALUES"),
	VALUE_DEF:           Symbol("VALUE_DEF"),
	VALUE_DATA:          Symbol("VALUE_DATA"),
	SET_VALUE_DATA:      Symbol("SET_VALUE_DATA"),
	VALUE_CB:            Symbol("VALUE_CB"),
	EVENTS:              Symbol("EVENTS"),
	VERIFIED:		         Symbol("VERIFIED"),

	// functions & data in mappings
	DESTROY:             Symbol("DESTROY"),
	SET_ATTR_DATA:       Symbol("SET_ATTR_DATA"),
	SET_VALUE:           Symbol("SET_VALUE"),

	ACTION_EXEC:         Symbol("ACTION_EXEC"),
	ACTION_DEF:          Symbol("ACTION_DEF"),

	EVENT_FIRE:          Symbol("EVENT_FIRE"),
	EVENT_DEF:           Symbol("EVENT_DEF"),
	EVENT_CB:            Symbol("EVENT_CB"),


	// device callbacks calld by coordinator.
	ON_ENDPOINT_ADD:     Symbol("ON_ENDPOINT_ADD"),
	ON_CLUSTER_ADD:      Symbol("ON_CLUSTER_ADD"),
	ON_ATTRIBUTE_ADD:    Symbol("ON_ATTRIBUTE_ADD"),
	ON_ATTRIBUTE_CHANGE: Symbol("ON_ATTRIBUTE_CHANGE"),
	ON_COMMAND_ADD:      Symbol("ON_COMMAND_ADD"),
	ON_VALUE_ADD:        Symbol("ON_VALUE_ADD"),
	ON_VALUE_REMOVE:     Symbol("ON_VALUE_REMOVE"),
	ON_ACTION_ADD:       Symbol("ON_ACTION_ADD"),
	ON_ACTION_REMOVE:    Symbol("ON_ACTION_REMOVE"),
	ON_ACTION_EXEC:      Symbol("ON_ACTION_EXEC"),
	ON_EVENT_ADD:        Symbol("ON_EVENT_ADD"),
	ON_EVENT_REMOVE:     Symbol("ON_EVENT_REMOVE"),
	ON_EVENT_FIRE:       Symbol("ON_EVENT_FIRE"),
};
